# Generated by Django 2.0 on 2017-09-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_principal', models.CharField(max_length=100)),
                ('accompagnement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrée',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_principal', models.CharField(max_length=100)),
                ('accompagnement', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_principal', models.CharField(max_length=100)),
                ('accompagnement', models.CharField(max_length=100)),
            ],
        ),
    ]
