# Generated by Django 2.0 on 2017-09-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dessert',
            old_name='plat_principal',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='entrée',
            old_name='plat_principal',
            new_name='principal',
        ),
        migrations.RenameField(
            model_name='plat',
            old_name='plat_principal',
            new_name='principal',
        ),
    ]
